apiVersion: v1
kind: ServiceAccount
metadata:
  name: cost-manager
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ .Values.serviceAccount.annotations | toYaml | indent 4 }}
{{- end }}
