image:
  pullPolicy: IfNotPresent
  # TODO(dippynark): Use HSBC Docker Hub repository
  repository: docker.io/dippynark/cost-manager
  tag: ""

cloudProvider: fake

serviceAccount:
  annotations: {}

# Create VPA to vertically autoscale cost-manager:
# https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler
vpa:
  enabled: false
