image:
  # TODO(dippynark): Use HSBC Docker Hub repository
  repository: docker.io/dippynark/cost-manager
  tag: latest
  pullPolicy: IfNotPresent

config:
  apiVersion: cost-manager.io/v1alpha1
  kind: CostManagerConfiguration

serviceAccount:
  annotations: {}

# Create VPA to vertically autoscale cost-manager:
# https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler
vpa:
  enabled: false

prometheusRule:
  enabled: false
  groups:
    rules:
      labels: {}
      annotations: {}

podMonitor:
  enabled: false
