# https://github.com/kubernetes-sigs/kubebuilder-release-tools#pr-verification-github-action
name: pr
on:
  # pull_request_target runs in the context of the base of the pull request so changes won't take
  # effect until this file is merged into the main branch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
jobs:
  verify:
    runs-on: ubuntu-latest
    name: verify
    steps:
    - name: Verifier action
      uses: kubernetes-sigs/kubebuilder-release-tools@v0.4.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
